### ISSUE TITLE
Should the top-images in building and room view be smaller?

### ISSUE THREAD

**Issue by Freheims** [eddiman/Romplan_UiB#20]
Currently the image takes up about 2/3 of the screen, that combined with the room image in the building view and the first hour of the calendar (which usually is empty) in the room view, which leads to no usable information in the screen so that the user has to scroll down to actually see something. 

Maybe we should consider to shrink the images to a more fitting size? E.g. 1/3 of the screen-height?

![15126100_1133387803377751_864033380_o](https://cloud.githubusercontent.com/assets/11025842/20481098/c6072a80-afe5-11e6-881e-b4eb653626db.png)
![15152272_1133387833377748_169092982_o](https://cloud.githubusercontent.com/assets/11025842/20481102/ca59da4c-afe5-11e6-9388-2aab47debd7f.png)

**Comment by eddiman** [comment]
Set to 2/5 of screen height, from now on.
